name=GDTouchKeyboard
version=1.0.0
author=GWENDESIGN
maintainer=GWENDESIGN
sentence=Touch keyboard for M5Unified.
paragraph=Touch keyboard library for M5Unified with configurable keyboard modes, input length limits, validation callbacks, and custom themes.
category=Display
url=https://github.com/matthias-bs/GDTouchKeyboard
architectures=esp32
depends=M5Unified
